zuul:
  routes:
    products:
      path: /api/products/**
      stripPrefix: false
      serviceId: products
  retryable: true

products:
  ribbon:
    NFLoadBalancerRuleClassName: com.example.zuulgateway.loadBalanceRole.MyRandomRule
    listOfServers: http://localhost:8081, http://localhost:8082, http://localhost:8083, http://localhost:8084
    retryableStatusCodes: 404,500
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 3
    OkToRetryOnAllOperations: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    show-sql: true

server:
  port: 8080