zuul:
  routes:
    products:
      path: /api/products/**
      stripPrefix: false
      serviceId: products

products:
  ribbon:
    NFLoadBalancerRuleClassName: com.example.zuulgateway.loadBalanceRole.TimesWeightBaseRule
    listOfServers: http://localhost:8081, http://localhost:8082

server:
  port: 8080