zuul:
  routes:
    products:
      path: /api/products/**
      stripPrefix: false
      serviceId: store-product
      retryable: true
    orders:
      path: /api/users/*/orders/**
      stripPrefix: false
      serviceId: store-order
      retryable: true

ribbon:
  retryableStatusCodes: 404,500
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 3
  OkToRetryOnAllOperations: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    show-sql: true

  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8079/eureka

server:
  port: 8080