zuul:
  routes:
    products:
      path: /api/products/**
      stripPrefix: false
      serviceId: products
  retryable: true

products:
  ribbon:
    NFLoadBalancerRuleClassName: com.example.zuulgateway.loadBalanceRole.MyRandomRule
    listOfServers: http://localhost:8081, http://localhost:8082, http://localhost:8083
    retryableStatusCodes: 404,500
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    OkToRetryOnAllOperations: true

server:
  port: 8080